HPI/HPIApp/Areas/Customer/Controllers/DashboardController.cs
using HPIApp.DataAccess.Repository;
using HPIApp.Models.ViewModel;
using HPIApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace HPIApp.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = StaticDetails.ROLE_CUSTOMER)]
    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var claim = _unitOfWork.ApplicationUser.GetUserClaims((ClaimsIdentity)User.Identity).GetAwaiter().GetResult().Value;
            UserTransactionVM userTransactionVM = new();

            userTransactionVM.transaction = await _unitOfWork
                .Transaction
                .GetFirstOrDefaultAsync(x => 
                x.ApplicationUserId == claim && 
                x.TransactionType == StaticDetails.PAYMENTTYPE_REGISTRATION);

            return View(userTransactionVM);
        }
    }
}

HPI/HPIApp/Areas/Customer/Controllers/HomeController.cs
using HPIApp.Areas.Identity.Pages.Account;
using HPIApp.DataAccess.Repository;
using HPIApp.Models;
using HPIApp.Models.ViewModel;
using HPIApp.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HPIApp.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public HomeController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            if(User.IsInRole(StaticDetails.ROLE_CUSTOMER))
            {
                return LocalRedirect("~/Customer/Dashboard");
            }
            else if(User.IsInRole(StaticDetails.ROLE_ADMIN))
            {
                return LocalRedirect("~/Admin/Dashboard");
            }
            else
            {
                CustomerIndexVM CustomerIndexVM = new()
                {
                    companyDetails = await _unitOfWork.CompanyDetails.GetFirstOrDefaultAsync(x => x.Id == 1),
                    heroSection = await _unitOfWork.HeroSection.GetFirstOrDefaultAsync(x => x.Id == 1),
                    whyUsSection = await _unitOfWork.WhyUsSection.GetFirstOrDefaultAsync(x => x.Id == 1),
                    aboutUsSection = await _unitOfWork.AboutUsSection.GetFirstOrDefaultAsync(x => x.Id == 1),
                    eventsSection = await _unitOfWork.EventSection.GetFirstOrDefaultAsync(x => x.Id == 1),
                    faqSection = await _unitOfWork.FAQSection.GetAllAsync(),
                    testimonialSection = await _unitOfWork.TestimonialSection.GetAllAsync(x => x.isAdded == true, includeProperties: "ApplicationUser"),
                    gallerySection = await _unitOfWork.GallerySection.GetAllAsync()
                };

                return View(CustomerIndexVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertContact(CustomerIndexVM CustomerIndexVM)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.ContactSection.AddAsync(CustomerIndexVM.contactSection);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Your message has been sent. Thank you!";
            }

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HPI/HPIApp/ViewComponents/FooterViewComponent.cs
using HPIApp.DataAccess.Repository;
using HPIApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace HPIApp.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public FooterViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            CustomerIndexVM customerIndexVM = new()
            {
                logo = await _unitOfWork.Logo.GetFirstOrDefaultAsync(x => x.Id == 1),
                companyDetails = await _unitOfWork.CompanyDetails.GetFirstOrDefaultAsync(x => x.Id == 1),
            };
            return View(customerIndexVM);
        }
    }
}

HPI/HPIApp/ViewComponents/IconViewComponent.cs
using HPIApp.DataAccess.Repository;
using HPIApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace HPIApp.ViewComponents
{
    public class IconViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public IconViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            CustomerIndexVM customerIndexVM = new()
            {
                logo = await _unitOfWork.Logo.GetFirstOrDefaultAsync(x => x.Id == 1)
            }; 
            return View(customerIndexVM);
        }
    }
}

HPI/HPIApp/ViewComponents/LogoViewComponent.cs
using HPIApp.DataAccess.Repository;
using HPIApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace HPIApp.ViewComponents
{
    public class LogoViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public LogoViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            CustomerIndexVM customerIndexVM = new()
            {
                logo = await _unitOfWork.Logo.GetFirstOrDefaultAsync(x => x.Id == 1)
            };
            return View(customerIndexVM);
        }
    }
}

HPI/HPIApp/ViewComponents/TopBarViewComponent.cs
using HPIApp.DataAccess.Repository;
using HPIApp.Models;
using HPIApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace HPIApp.ViewComponents
{
    public class TopBarViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public TopBarViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            CustomerIndexVM customerIndexVM = new()
            {
                companyDetails = await _unitOfWork.CompanyDetails.GetFirstOrDefaultAsync(x => x.Id == 1),
            };
            return View(customerIndexVM);
        }
    }
}

HPI/HPIApp/Views/Shared/Customer/_AboutUsLayout.cshtml
@model CustomerIndexVM

<!-- ======= About Section ======= -->
<section id="about" class="about">
    <div class="container-fluid">

        <div class="row">
            @if(string.IsNullOrEmpty(Model.aboutUsSection.VideoBoxUrl))
            {
                <div class="col-xl-5 col-lg-6 d-flex justify-content-center align-items-stretch position-relative" style="background: url('https://placehold.co/1024x692/png') center center no-repeat; background-size: cover; min-height: 500px;">
                    <a href="@Model.aboutUsSection.VideoUrl" class="glightbox play-btn mb-4"></a>
                </div>
            }
            else
            {
                <div class="col-xl-5 col-lg-6 d-flex justify-content-center align-items-stretch position-relative" style="background: url('@Model.aboutUsSection.VideoBoxUrl.Replace("\\","/")') center center no-repeat; background-size: cover; min-height: 500px;">
                    <a href="@Model.aboutUsSection.VideoUrl" class="glightbox play-btn mb-4"></a>
                </div>
            }

            <div class="col-xl-7 col-lg-6 icon-boxes d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5">
                <h3>@Model.aboutUsSection.mainContentTitle</h3>
                <p>@Model.aboutUsSection.mainContentDescription</p>

                <div class="icon-box">
                    <div class="icon"><i class="bx bx-fingerprint"></i></div>
                    <h4 class="title"><a href="">@Model.aboutUsSection.contentTitle_1</a></h4>
                    <p class="description">@Model.aboutUsSection.contentDescription_1</p>
                </div>

                <div class="icon-box">
                    <div class="icon"><i class="bx bx-gift"></i></div>
                    <h4 class="title"><a href="">@Model.aboutUsSection.contentTitle_2</a></h4>
                    <p class="description">@Model.aboutUsSection.contentDescription_2</p>
                </div>

                <div class="icon-box">
                    <div class="icon"><i class="bx bx-atom"></i></div>
                    <h4 class="title"><a href="">@Model.aboutUsSection.contentTitle_3</a></h4>
                    <p class="description">@Model.aboutUsSection.contentDescription_3</p>
                </div>

            </div>
        </div>

    </div>
</section><!-- End About Section -->

HPI/HPIApp/Views/Shared/Customer/_ContactLayout.cshtml
@model CustomerIndexVM

<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container">

        <div class="section-title">
            <h2>Contact</h2>
        </div>
    </div>

    <div>
        <iframe style="border:0; width: 100%; height: 350px;" frameborder="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3612.153089227167!2d121.13417132915704!3d15.629524036959644!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3390cc5718e395df%3A0x76ee7b2815e46464!2sPalo%20Maria%20(Pob.)%2C%20Bongabon%2C%20Nueva%20Ecija!5e1!3m2!1sen!2sph!4v1683880795988!5m2!1sen!2sph" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="container">
        <div class="row mt-5">

            <div class="col-lg-4">
                <div class="info">
                    <div class="address">
                        <i class="bi bi-geo-alt"></i>
                        <h4>Location:</h4>
                        <p>@Model.companyDetails.Address</p>
                    </div>

                    <div class="email">
                        <i class="bi bi-envelope"></i>
                        <h4>Email:</h4>
                        <p>@Model.companyDetails.Email</p>
                    </div>

                    <div class="phone">
                        <i class="bi bi-phone"></i>
                        <h4>Call:</h4>
                        <p>@Model.companyDetails.PhoneNo</p>
                    </div>

                </div>

            </div>

            <div class="col-lg-8 mt-5 mt-lg-0">

                <form asp-area="Customer" asp-controller="Home" asp-action="InsertContact" method="post">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input asp-for="contactSection.Name" type="text" class="form-control" id="name" placeholder="Your Name">
                            <span asp-validation-for="contactSection.Name" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <input asp-for="contactSection.Email" type="email" class="form-control" id="email" placeholder="Your Email">
                            <span asp-validation-for="contactSection.Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <input asp-for="contactSection.Subject" type="text" class="form-control" id="subject" placeholder="Subject">
                        <span asp-validation-for="contactSection.Subject" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <textarea asp-for="contactSection.Message" class="form-control" rows="5" placeholder="Message"></textarea>
                        <span asp-validation-for="contactSection.Message" class="text-danger"></span>
                    </div>
                    <div class="text-center py-2">
                        <button onclick="return SendButton();" type="submit" class="contactSection">Send Message</button>
                    </div>
                </form>

            </div>

        </div>

    </div>
</section><!-- End Contact Section -->

HPI/HPIApp/Views/Shared/Customer/_EventsLayout.cshtml
@model CustomerIndexVM

@if (!string.IsNullOrEmpty(Model.eventsSection.EventDescription))
{
    <!-- ======= Events Section ======= -->
    <section id="events" class="events section-bg">
        <div class="container">

            <div class="section-title">
                <h2>Events</h2>
                <p>@Model.eventsSection.EventDescription</p>
            </div>

        </div>
    </section>

    <!-- End Events Section -->
}

HPI/HPIApp/Views/Shared/Customer/_FAQLayout.cshtml
@model CustomerIndexVM

@if (Model.faqSection.Count() > 0)
{
    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq section-bg">
        <div class="container">

            <div class="section-title">
                <h2>Frequently Asked Questions</h2>
            </div>

            <div class="faq-list">
                <ul>

                    @foreach (var faq in Model.faqSection)
                    {
                        <li data-aos="fade-up" data-aos-delay="100">
                            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-@faq.Id" class="collapsed">@faq.Question<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                            <div id="faq-list-@faq.Id" class="collapse" data-bs-parent=".faq-list">
                                <p>@faq.Answer</p>
                            </div>
                        </li>
                    }

                </ul>
            </div>

        </div>
    </section>

    <!-- End Frequently Asked Questions Section -->
}

HPI/HPIApp/Views/Shared/Customer/_GalleryLayout.cshtml
@model CustomerIndexVM

@if (Model.gallerySection.Count() > 0)
{
    <!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">
        <div class="container">

            <div class="section-title">
                <h2>Gallery</h2>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row g-0">

                @foreach (var image in Model.gallerySection)
                {
                    <div class="col-lg-3 col-md-4">
                        <div class="gallery-item">
                            <a href="@image.ImgUrl" class="galelry-lightbox">
                                <img src="@image.ImgUrl" alt="" class="img-fluid">
                            </a>
                        </div>
                    </div>
                }

            </div>

        </div>
    </section>

    <!-- End Gallery Section -->
}

HPI/HPIApp/Views/Shared/Customer/_HeaderLayout.cshtml
@model CustomerIndexVM

    @await Component.InvokeAsync("TopBar")

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            @await Component.InvokeAsync("Logo")    

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About Us</a></li>
                    <li><a class="nav-link scrollto" href="#events">Events</a></li>
                    <li><a class="nav-link scrollto" href="#faq">FAQ</a></li>
                    <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
            @if (!User.IsInRole(StaticDetails.ROLE_ADMIN) && !User.IsInRole(StaticDetails.ROLE_CUSTOMER))
            {
                <partial name="_LoginPartial" />
            }
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    @if(String.IsNullOrEmpty(Model.heroSection.backgroundImgUrl))
    {
        <section id="hero" class="d-flex align-items-center" style="background: url('https://placehold.co/1920x846/png') top center; background-attachment: fixed;">
            <div class="container">
                <h1>HEADER 1</h1>
                <h2>HEADER 2</h2>
                <a href="#about" class="btn-get-started scrollto">Get Started</a>
            </div>
        </section>
    
    }
    else
    {
        <section id="hero" class="d-flex align-items-center" style="background: url('@Model.heroSection.backgroundImgUrl.Replace("\\","/")') top center; background-attachment: fixed;">
            <div class="container">
                <h1>@Model.heroSection.Header1</h1>
                <h2>@Model.heroSection.Header2</h2>
                <a href="#about" class="btn-get-started scrollto">Get Started</a>
            </div>
        </section>
    }
    <!-- End Hero -->

HPI/HPIApp/Views/Shared/Customer/_InnerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    @await Component.InvokeAsync("Icon")

    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="/lib/customer/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="/lib/customer/animate.css/animate.min.css" rel="stylesheet">
    <link href="/lib/customer/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/lib/customer/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/lib/customer/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/lib/customer/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/lib/customer/remixicon/remixicon.css" rel="stylesheet">
    <link href="/lib/customer/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/css/customer.css" rel="stylesheet" asp-append-version="true">
</head>
<body>
    @await Component.InvokeAsync("TopBar")
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            @await Component.InvokeAsync("Logo")

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    @*<li><a class="nav-link scrollto active" href="#hero">Home</a></li>*@
                    @*<li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#departments">Departments</a></li>
                    <li><a class="nav-link scrollto" href="#doctors">Doctors</a></li>
                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>*@
                </ul>
                @*<i class="bi bi-list mobile-nav-toggle"></i>*@
            </nav><!-- .navbar -->
            @*<a href="#appointment" class="appointment-btn scrollto"><span class="d-none d-md-inline">Make an</span> Appointment</a>*@
            <partial name="_LoginPartial" />
        </div>
    </header><!-- End Header -->

    <main role="main" id="main">
        <section class="breadcrumbs"></section>
        <section class="inner-page">
            <div class="container">
                @RenderBody()
            </div>
        </section>
       
    </main>

    @await Component.InvokeAsync("Footer")

    <script src="/lib/customer/purecounter/purecounter_vanilla.js"></script>
    <script src="/lib/customer/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/customer/glightbox/js/glightbox.min.js"></script>
    <script src="/lib/customer/swiper/swiper-bundle.min.js"></script>
    <script src="~/js/customer.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HPI/HPIApp/Views/Shared/Customer/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">
    
    @await Component.InvokeAsync("Icon")

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link href="/lib/customer/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="/lib/customer/animate.css/animate.min.css" rel="stylesheet">
    <link href="/lib/customer/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/lib/customer/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/lib/customer/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/lib/customer/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/lib/customer/remixicon/remixicon.css" rel="stylesheet">
    <link href="/lib/customer/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="~/css/customer.css" rel="stylesheet" asp-append-version="true">
</head>
<body>
    
    <partial name="Customer/_HeaderLayout" />

    <main role="main" id="main">
        <partial name="_Notification" />
        @RenderBody()
    </main>

    @await Component.InvokeAsync("Footer")

    <script src="/lib/customer/purecounter/purecounter_vanilla.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="/lib/customer/glightbox/js/glightbox.min.js"></script>
    <script src="/lib/customer/swiper/swiper-bundle.min.js"></script>
    <script src="~/js/customer.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HPI/HPIApp/Views/Shared/Customer/_TestimonialLayout.cshtml
@model CustomerIndexVM

@if (Model.testimonialSection.Count() > 0)
{
    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
        <div class="container">

            <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
                <div class="swiper-wrapper">

                    @foreach (var testimony in Model.testimonialSection)
                    {
                        <div class="swiper-slide">
                            <div class="testimonial-wrap">
                                <div class="testimonial-item">
                                    <img src="@testimony.ApplicationUser.MemberPhotoUrl" class="testimonial-img" alt="">
                                    <h3>@testimony.ApplicationUser.FirstName @testimony.ApplicationUser.LastName</h3>
                                    <p>
                                        <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                                        @testimony.Testimony
                                        <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- End testimonial item -->
                    }

                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>
    </section>

    <!-- End Testimonials Section -->
}

HPI/HPIApp/Views/Shared/Customer/_WhyUsLayout.cshtml
@model CustomerIndexVM

<!-- ======= Why Us Section ======= -->
<section id="why-us" class="why-us">
    <div class="container">

        <div class="row">
            <div class="col-lg-4 d-flex align-items-stretch">
                <div class="content">
                    <h3>@Model.whyUsSection.mainContentTitle</h3>
                    <p>@Model.whyUsSection.mainContentDescription</p>
                </div>
            </div>
            <div class="col-lg-8 d-flex align-items-stretch">
                <div class="icon-boxes d-flex flex-column justify-content-center">
                    <div class="row">
                        <div class="col-xl-4 d-flex align-items-stretch">
                            <div class="icon-box mt-4 mt-xl-0">
                                <i class="bx bx-receipt"></i>
                                <h4>@Model.whyUsSection.contentTitle_1</h4>
                                <p>@Model.whyUsSection.contentDescription_1</p>
                            </div>
                        </div>
                        <div class="col-xl-4 d-flex align-items-stretch">
                            <div class="icon-box mt-4 mt-xl-0">
                                <i class="bx bx-cube-alt"></i>
                                <h4>@Model.whyUsSection.contentTitle_2</h4>
                                <p>@Model.whyUsSection.contentDescription_2</p>
                            </div>
                        </div>
                        <div class="col-xl-4 d-flex align-items-stretch">
                            <div class="icon-box mt-4 mt-xl-0">
                                <i class="bx bx-plus-medical"></i>
                                <h4>@Model.whyUsSection.contentTitle_3</h4>
                                <p>@Model.whyUsSection.contentDescription_3</p>
                            </div>
                        </div>
                    </div>
                </div><!-- End .content-->
            </div>
        </div>

    </div>
</section><!-- End Why Us Section -->