HPI/HPIApp/Areas/Admin/Controllers/DashboardController.cs
using HPIApp.Models;
using HPIApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HPIApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            ViewData["_AdminSidebar"] = new _AdminSidebar { view = "dashboard", navItem = "dashboard" };
            return View();
        }
    }
}

HPI/HPIApp/Areas/Admin/Controllers/PaymentMethodController.cs
using EntityFramework.Exceptions.Common;
using HPIApp.DataAccess.Repository;
using HPIApp.Models;
using HPIApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HPIApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.ROLE_ADMIN)]
    public class PaymentMethodController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PaymentMethodController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            ViewData["_AdminSidebar"] = new _AdminSidebar { view = "paymentMethod", navItem = "contentManagement" };
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            ViewData["_AdminSidebar"] = new _AdminSidebar { view = "paymentMethod", navItem = "userManagement" };

            PaymentMethod obj = new();

            if (id is null || id.Equals(0))
                return View(obj);

            obj = await _unitOfWork.PaymentMethod.GetFirstOrDefaultAsync(x => x.Id == id);

            if (obj is null)
                return View("_Error404");

            return View(obj);
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(PaymentMethod obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id.Equals(0))
                {
                    await _unitOfWork.PaymentMethod.AddAsync(obj);
                    TempData["success"] = "Payment Method created successfully.";
                }
                else
                {
                    await _unitOfWork.PaymentMethod.Update(obj);
                    TempData["success"] = "Payment Method updated successfully.";
                }

                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(obj);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                var PaymentMethodObj = await _unitOfWork.PaymentMethod.GetFirstOrDefaultAsync(x => x.Id == id);

                if (PaymentMethodObj is null) return Json(new { error = false, message = "Error while deleting." });

                await _unitOfWork.PaymentMethod.Remove(PaymentMethodObj);
                await _unitOfWork.SaveAsync();
                return Json(new { success = true, message = "Payment Method deleted successfully." });
            }
            catch (ReferenceConstraintException ex)
            {
                return Json(new { error = true, message = "Error while deleting. " + ex.Message });
            }
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var paymentMethodList = await _unitOfWork.PaymentMethod.GetAllAsync();
            return Json(new { data = paymentMethodList });
        }
        #endregion
    }
}

HPI/HPIApp/Areas/Admin/Views/PaymentMethod/Index.cshtml
<partial name="Admin/_AdminSidebar" />

<div class="pagetitle">
    <h1>Payment Method</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item">Payment Method</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow border-0 mt-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="card-title">Payment Method List</h5>
                        </div>

                        <div class="col-6 text-end">
                            <a asp-controller="PaymentMethod" asp-action="Upsert" class="btn btn-primary mt-3">
                                <i class="bi bi-plus-circle"></i> &nbspAdd New Payment Method
                            </a>
                        </div>
                    </div>
                    </br></br>

                    <table id="tblPaymentMethod" class="table table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Name</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
    {
    <script src="~/js/admin/paymentmethod.js"></script>
}

HPI/HPIApp/Areas/Admin/Views/PaymentMethod/Upsert.cshtml
@model PaymentMethod

<partial name="Admin/_AdminSidebar" />

<div class="pagetitle">
    <h1>Payment Method</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item"><a asp-controller="PaymentMethod" asp-action="Index">Payment Method</a></li>
            <li class="breadcrumb-item">@(Model.Id == 0 ? "Create" : "Edit") Payment Method</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow border-0 w-75 top-50 start-50 translate-middle">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="card-title">@(Model.Id == 0 ? "Create" : "Edit") Payment Method</h5>
                        </div>
                    </div>

                    <section class="section">
                        <form method="post" asp-action="Upsert">
                            <input asp-for="Id" hidden />
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-floating py-2 col-12">
                                        <input asp-for="Name" class="form-control border-0 shadow" placeholder="Enter name" />
                                        <label asp-for="Name" class="ms-2 text-muted"></label>
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="row pt-2">
                                        <div class="col-6 col-md-3">
                                            @if (Model.Id == 0)
                                            {
                                                <button type="submit" class="btn btn-primary form-control">
                                                    <i class="bi bi-plus-circle"></i> &nbspCreate
                                                </button>
                                            }
                                            else
                                            {
                                                <button type="submit" class="btn btn-primary form-control">
                                                    <i class="bi bi-plus-circle"></i> &nbspUpdate
                                                </button>
                                            }
                                        </div>
                                        <div class="col-6 col-md-3">
                                            <a asp-controller="PaymentMethod" asp-action="Index" class="btn btn-outline-primary form-control">
                                                <i class="bi bi-backspace"></i> &nbspBack
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"></partial>
}